using System;
using System.Collections.Generic;
using System.Linq;

namespace SweepStakesProject
{
    public class SweepStakes

    {
        

        //Member variables

        public string name;
        public int maxNumberOfContestants;
        int counter;
        int theWinningNumber;
        Dictionary<int, Contestant> Contestants = new Dictionary<int, Contestant>();


        //Constructor

        public SweepStakes(string name)

        {
            this.name = name;
            maxNumberOfContestants = UserInterface.ManageNumberOfContestants(name);
            counter = 1;
        }
        //Methods



        //Sweepstakes(string name)--- Done
        //void RegisterContestant(Contestant contestant)-- Done but fix errors
        //string PickWinner()
        //void PrintContestantInfo(Contestant contestant)-- Done
        //Dictionary data needed--Done

        public string RunSweepStakes()
        {
            for (int i = 1; i == maxNumberOfContestants; i++)
            {

                Contestant contestant = new Contestant();
                RegisterContestant(contestant);

                //contestant is the player inputting information which is also getting
                //registered

            }

            string winner = PickWinner();
            Console.WriteLine(winner);
            return winner;



        }



        public void RegisterContestant(Contestant contestant)
        {
            contestant.firstName = UserInterface.GetFirstName();
            

            contestant.lastName = UserInterface.GetLastName();
            

            contestant.emailAddress = UserInterface.GetEmail();


            contestant.registrationNumber = counter;
            counter++;

            Contestants.Add(contestant.registrationNumber, contestant); 
            

            Console.WriteLine("Is all of the following information correct? y/n.");
            PrintContestantInfo(contestant);

        }


        public string PickWinner()
            // "WinningContestant" is the object. Since you created the randomizer, [theWinningNumber] will be generated by the randomizer
            // winnerName string will pull the actual Contestants information that was entered to then declare the winner
        {
            Random random = new Random();
            theWinningNumber = random.Next(1, Contestants.Count);
            
            Contestant WinningContestant = Contestants[theWinningNumber];
            string winnerName = WinningContestant.firstName + " " + WinningContestant.lastName;  

            return winnerName;
        }



        public void PrintContestantInfo(Contestant contestant)
        {

            Console.WriteLine(contestant.firstName);
            Console.WriteLine(contestant.lastName);
            Console.WriteLine(contestant.emailAddress);
            Console.WriteLine(contestant.registrationNumber);


        }
    }
}

